dist: xenial
node_js: '10'
cache: npm
services:
- docker

script:
    - docker build -t maheshsawaiker/cw-marketing . 
    - echo "$DOCKER_HUB_KEY" | docker login -u maheshsawaiker --password-stdin
    - docker push maheshsawaiker/cw-marketing:latest