apiVersion: apps/v1
kind: Deployment
metadata:
  name: cw-marketing
  labels:
    app: cw-marketing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cw-marketing
  template:
    metadata:
      labels:
        app: cw-marketing
    spec:
      containers:
      - name: cw-marketing
        image: maheshsawaiker/cw-marketing
        ports:
        - containerPort: 5000